### ISSUE TITLE
Can't install puppetdb on CentOS 7.2 vagrant box by puppet

### ISSUE THREAD

**Issue by vzabawski** [example42/puppet-puppetdb#18]
## Expected Behavior

PuppetDB installation
## Actual Behavior

Getting the following error:

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not find class ::yum::repo::puppetlabs for puppetmaster at /etc/puppetlabs/code/environments/production/modules/puppetdb/manifests/prerequisites.pp:21:7 on node puppetmaster`
## Steps to Reproduce the Problem
1. Install example42/puppetdb  module
2. Add **puppetdb** class to your puppetserver node

```
node puppetmaster {
class { 'puppetdb':
  db_type => 'postgresql',
}
}
```
1. Restart puppetserver
2. Run `puppet agent -t`
## Specifications

I'm running puppetserver inside Vagrant VM using puppet centos 7.2 box with preinstalled puppet.

Here's my repos

```
repo id                    repo name                                      status
base/7/x86_64              CentOS-7 - Base                                 9,007
epel/x86_64                Extra Packages for Enterprise Linux 7 - x86_64 10,494
extras/7/x86_64            CentOS-7 - Extras                                 375
passenger/7/x86_64         passenger                                         176
passenger-source/7         passenger-source                                    0
puppetlabs-deps/x86_64     Puppet Labs Dependencies El 7 - x86_64             17
puppetlabs-pc1/x86_64      Puppet Labs PC1 Repository el 7 - x86_64           86
puppetlabs-products/x86_64 Puppet Labs Products El 7 - x86_64                222
updates/7/x86_64           CentOS-7 - Updates                              2,298
repolist: 22,675
```

**Comment by alvagante** [comment]
The module needs examples42/yum module to manage the puppetlabs repo.
Since you have already it, you can disable this prerequisite with:

``` puppet
class { 'puppetdb':
 install_prerequisites => false,
}
```

Note however that this is quite an old module which is no more maintained. It may not work correctly with recent versions of PuppetDB
